"""
DRF provides two possible routers:
1. SimpleRouter
    - reference: https://www.django-rest-framework.org/api-guide/routers/#simplerouter
2. DefaultRouter
    - reference: https://www.django-rest-framework.org/api-guide/routers/#defaultrouter
    
Since the DefaultRouter includes a default API root view, making it easier to navigate the Browsable API, 
we'll use this one.    

Browsable API reference:
https://www.django-rest-framework.org/topics/browsable-api/


The register() method has three arguments:

1. prefix (required) - URL prefix for the ViewSet
2. viewset (required) - The ViewSet class
3. basename (optional) - The base to use for the URL names
While the basename is generated by default from the QuerySet,
it's a good idea to be explicit and define it for clarity purposes.
"""

from django.urls import path, include
from rest_framework import routers

from shopping_list.api.viewsets import ShoppingItemViewSet


router = routers.DefaultRouter()
router.register("shopping-items", ShoppingItemViewSet, basename="shopping-items")

urlpatterns = [
    path("api/", include(router.urls)),
]
